name: DeployToJoomlaVM

# Trigger the workflow on push and 
# pull request events on the production branch
on:
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main2
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
# Authenticate to the the server via ssh 
# and run our deployment script 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.J_HOST }}
          username: ${{ secrets.J_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.J_SSHKEY }}
          script: "cd ${{ secrets.HOME_DIR }} && ./.scripts/deploy.sh"
